all: Exos1 Exos2 Exos3 Exos4 

# apres l'etiquete (test:) un .o pour chaque .cpp compilé
# cette ligne genere un executable appele 'test'
Exos1: Exos1.cpp
	g++ -Wall Exos1.cpp -o Exos1

Exos2: Exos2.cpp
	g++ -Wall Exos2.cpp -o Exos2

Exos3: Exos3.cpp
	g++ -Wall Exos3.cpp -o Exos3

Exos4: Exos4.cpp
	g++ -Wall Exos4.cpp -o Exos4

clean:
	rm -f *.o test
